//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appius.MOCompute.Services.Client.Prototype.ComputeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComputeService.IComputeService")]
    public interface IComputeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Noop", ReplyAction="http://tempuri.org/IService/NoopResponse")]
        string Noop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Noop", ReplyAction="http://tempuri.org/IService/NoopResponse")]
        System.Threading.Tasks.Task<string> NoopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputeService/GetResults", ReplyAction="http://tempuri.org/IComputeService/GetResultsResponse")]
        void GetResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComputeService/GetResults", ReplyAction="http://tempuri.org/IComputeService/GetResultsResponse")]
        System.Threading.Tasks.Task GetResultsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComputeServiceChannel : Appius.MOCompute.Services.Client.Prototype.ComputeService.IComputeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComputeServiceClient : System.ServiceModel.ClientBase<Appius.MOCompute.Services.Client.Prototype.ComputeService.IComputeService>, Appius.MOCompute.Services.Client.Prototype.ComputeService.IComputeService {
        
        public ComputeServiceClient() {
        }
        
        public ComputeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComputeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComputeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Noop() {
            return base.Channel.Noop();
        }
        
        public System.Threading.Tasks.Task<string> NoopAsync() {
            return base.Channel.NoopAsync();
        }
        
        public void GetResults() {
            base.Channel.GetResults();
        }
        
        public System.Threading.Tasks.Task GetResultsAsync() {
            return base.Channel.GetResultsAsync();
        }
    }
}
