//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appius.MOCompute.Services.Client.Prototype.LocationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Appius.MOCompute.Services.Services.Entiti" +
        "es")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocationService.ILocationService")]
    public interface ILocationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Noop", ReplyAction="http://tempuri.org/IService/NoopResponse")]
        string Noop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Noop", ReplyAction="http://tempuri.org/IService/NoopResponse")]
        System.Threading.Tasks.Task<string> NoopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/ListAll", ReplyAction="http://tempuri.org/ILocationService/ListAllResponse")]
        Appius.MOCompute.Services.Client.Prototype.LocationService.Location[] ListAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/ListAll", ReplyAction="http://tempuri.org/ILocationService/ListAllResponse")]
        System.Threading.Tasks.Task<Appius.MOCompute.Services.Client.Prototype.LocationService.Location[]> ListAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/List", ReplyAction="http://tempuri.org/ILocationService/ListResponse")]
        Appius.MOCompute.Services.Client.Prototype.LocationService.Location[] List(string AlphaCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/List", ReplyAction="http://tempuri.org/ILocationService/ListResponse")]
        System.Threading.Tasks.Task<Appius.MOCompute.Services.Client.Prototype.LocationService.Location[]> ListAsync(string AlphaCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationServiceChannel : Appius.MOCompute.Services.Client.Prototype.LocationService.ILocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationServiceClient : System.ServiceModel.ClientBase<Appius.MOCompute.Services.Client.Prototype.LocationService.ILocationService>, Appius.MOCompute.Services.Client.Prototype.LocationService.ILocationService {
        
        public LocationServiceClient() {
        }
        
        public LocationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Noop() {
            return base.Channel.Noop();
        }
        
        public System.Threading.Tasks.Task<string> NoopAsync() {
            return base.Channel.NoopAsync();
        }
        
        public Appius.MOCompute.Services.Client.Prototype.LocationService.Location[] ListAll() {
            return base.Channel.ListAll();
        }
        
        public System.Threading.Tasks.Task<Appius.MOCompute.Services.Client.Prototype.LocationService.Location[]> ListAllAsync() {
            return base.Channel.ListAllAsync();
        }
        
        public Appius.MOCompute.Services.Client.Prototype.LocationService.Location[] List(string AlphaCode) {
            return base.Channel.List(AlphaCode);
        }
        
        public System.Threading.Tasks.Task<Appius.MOCompute.Services.Client.Prototype.LocationService.Location[]> ListAsync(string AlphaCode) {
            return base.Channel.ListAsync(AlphaCode);
        }
    }
}
